### ISSUE TITLE
Riverbank centerlines

### ISSUE THREAD

**Issue by StyXman** [ungarj/label_centerlines#1]
I will try to use this tool to semi automatically generate centerlines for riverbanks which have none. The problem is that it's only finding centerlines for segments that are wide enough, and it seems that there's no way to control the minimum width. I'm proficient in Python, but I know nothing about these types of algorithms, so if you could at least point me in the right direction, I could probably send a PR.

**Comment by StyXman** [comment]
In fact this algorithm does not properly work for what I want :( On narrow sections, Voronoi ridge vertices start falling out of the shape. [Here's an example of an atual riverbank.](http://grulicueva.homenet.org/~mdione/PhotoShow/?t=Img&f=sshots%2Friverbank_centerline_2.png) The red line is what this algo finds as the center line. 

I'll keep looking for a way to separate the actual riverbanks from the segments that just 'cross' the river.

**Comment by ungarj** [comment]
Hi, first of all, thanks for contributing!

I never tried the algorithm on riverbanks but theoretically it should work as well. Looking at your example, maybe it helps to decrease the segmentize value. The algorithm then puts the points closer together before drawing the voronoi and if they are close enough, there should be a centerline.

However there could be the issue that the algorithm incredibly slows down because the biggest performance issue with the current system is to extract the longest line from the voronoi. And the effort increases for every additional segmentize point.

**Comment by StyXman** [comment]
In `#osm` they pointed me to [PostGIS' `ST_ApproximateMedialAxis`](http://postgis.net/docs/ST_ApproximateMedialAxis.html). This looks more like what I actually want, but assumes your data is already in PostGIS (which I do). Maybe you could check out the algo for your script.
